-- =============================================================================
-- TrialGuard AI — Supabase Database Schema
-- =============================================================================
-- Run this in the Supabase SQL Editor to create all tables.
-- This schema stores clinical trial data, detected deviations, risk profiles,
-- and CAPA reports generated by the analysis engine.
-- =============================================================================

-- ─── Sites ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sites (
  site_id TEXT PRIMARY KEY,
  site_name TEXT NOT NULL,
  city TEXT NOT NULL,
  country TEXT NOT NULL,
  principal_investigator TEXT NOT NULL,
  is_problem_site BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─── Patients ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS patients (
  patient_id TEXT PRIMARY KEY,
  site_id TEXT NOT NULL REFERENCES sites(site_id) ON DELETE CASCADE,
  enrollment_date DATE NOT NULL,
  age INTEGER NOT NULL,
  sex TEXT NOT NULL CHECK (sex IN ('M', 'F')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─── Patient Visits ──────────────────────────────────────────────────────────
-- Core records that are checked against the protocol specification.
CREATE TABLE IF NOT EXISTS patient_visits (
  visit_id TEXT PRIMARY KEY,
  patient_id TEXT NOT NULL REFERENCES patients(patient_id) ON DELETE CASCADE,
  site_id TEXT NOT NULL REFERENCES sites(site_id) ON DELETE CASCADE,
  visit_number INTEGER NOT NULL,
  visit_name TEXT NOT NULL,
  scheduled_date DATE NOT NULL,
  actual_date DATE,                  -- NULL = missed visit
  protocol_target_day INTEGER NOT NULL,
  actual_day INTEGER,
  dose_administered_mg FLOAT,
  protocol_dose_mg FLOAT NOT NULL,
  assessments_completed TEXT[] DEFAULT '{}',
  assessments_required TEXT[] DEFAULT '{}',
  active_medications TEXT[] DEFAULT '{}',
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─── Detected Deviations ─────────────────────────────────────────────────────
-- Output of the deviation detection + severity classification pipeline.
CREATE TABLE IF NOT EXISTS deviations (
  deviation_id TEXT PRIMARY KEY,
  patient_id TEXT NOT NULL REFERENCES patients(patient_id) ON DELETE CASCADE,
  site_id TEXT NOT NULL REFERENCES sites(site_id) ON DELETE CASCADE,
  visit_id TEXT NOT NULL REFERENCES patient_visits(visit_id) ON DELETE CASCADE,
  visit_name TEXT NOT NULL,
  deviation_type TEXT NOT NULL,
  description TEXT NOT NULL,
  expected_value TEXT NOT NULL,
  actual_value TEXT NOT NULL,
  detected_date DATE,
  protocol_reference TEXT NOT NULL,
  severity TEXT,                     -- 'major' | 'minor' | 'administrative'
  raw_data JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─── Site Risk Profiles ──────────────────────────────────────────────────────
-- Output of the composite risk scoring engine.
CREATE TABLE IF NOT EXISTS site_risk_profiles (
  site_id TEXT PRIMARY KEY REFERENCES sites(site_id) ON DELETE CASCADE,
  site_name TEXT NOT NULL,
  risk_score FLOAT NOT NULL DEFAULT 0,
  risk_tier TEXT NOT NULL DEFAULT 'low',
  trend_direction TEXT NOT NULL DEFAULT 'stable',
  total_deviations INTEGER DEFAULT 0,
  major_count INTEGER DEFAULT 0,
  minor_count INTEGER DEFAULT 0,
  administrative_count INTEGER DEFAULT 0,
  deviation_types JSONB DEFAULT '{}',
  patients_affected INTEGER DEFAULT 0,
  total_patients INTEGER DEFAULT 0,
  recent_deviations_30d INTEGER DEFAULT 0,
  repeat_deviation_types TEXT[] DEFAULT '{}',
  top_risk_factors JSONB DEFAULT '[]',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─── CAPA Reports ────────────────────────────────────────────────────────────
-- Generated Corrective and Preventive Action reports, cached for retrieval.
CREATE TABLE IF NOT EXISTS capa_reports (
  report_id TEXT PRIMARY KEY,
  site_id TEXT NOT NULL REFERENCES sites(site_id) ON DELETE CASCADE,
  site_name TEXT NOT NULL,
  generated_date DATE NOT NULL,
  executive_summary TEXT,
  total_findings INTEGER DEFAULT 0,
  severity_breakdown JSONB DEFAULT '{}',
  ich_classification TEXT,
  overall_risk_level TEXT,
  root_cause_analysis TEXT,
  contributing_factors TEXT[] DEFAULT '{}',
  corrective_actions JSONB DEFAULT '[]',
  preventive_actions JSONB DEFAULT '[]',
  timeline_summary TEXT,
  next_review_date TEXT,
  full_report_markdown TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─── Users (Authentication) ──────────────────────────────────────────────────
-- Stores user accounts for the TrialGuard AI dashboard login system.
-- Demo accounts (judge, reviewer, admin) are seeded via db/seed.py.
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'reviewer' CHECK (role IN ('admin', 'reviewer', 'judge')),
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─── Indexes ─────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_patients_site ON patients(site_id);
CREATE INDEX IF NOT EXISTS idx_visits_site ON patient_visits(site_id);
CREATE INDEX IF NOT EXISTS idx_visits_patient ON patient_visits(patient_id);
CREATE INDEX IF NOT EXISTS idx_deviations_site ON deviations(site_id);
CREATE INDEX IF NOT EXISTS idx_deviations_severity ON deviations(severity);
CREATE INDEX IF NOT EXISTS idx_deviations_type ON deviations(deviation_type);
CREATE INDEX IF NOT EXISTS idx_risk_profiles_tier ON site_risk_profiles(risk_tier);
CREATE INDEX IF NOT EXISTS idx_risk_profiles_score ON site_risk_profiles(risk_score DESC);

-- ─── Row Level Security (production-ready) ───────────────────────────────────
-- Enable RLS on all tables (currently allow all for development)
ALTER TABLE sites ENABLE ROW LEVEL SECURITY;
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient_visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE deviations ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_risk_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE capa_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Development policies: allow all access via service role and anon key
CREATE POLICY "Allow all access" ON sites FOR ALL USING (true);
CREATE POLICY "Allow all access" ON patients FOR ALL USING (true);
CREATE POLICY "Allow all access" ON patient_visits FOR ALL USING (true);
CREATE POLICY "Allow all access" ON deviations FOR ALL USING (true);
CREATE POLICY "Allow all access" ON site_risk_profiles FOR ALL USING (true);
CREATE POLICY "Allow all access" ON capa_reports FOR ALL USING (true);
CREATE POLICY "Allow all access" ON users FOR ALL USING (true);
