-- =============================================================================
-- Migration 001 — Data Import Audit Table
-- =============================================================================
-- Run in the Supabase SQL Editor AFTER schema.sql.
-- Creates the audit/history table for hospital CSV/XLSX data uploads.
-- Stores counts only — NEVER row contents.
-- =============================================================================

CREATE TABLE IF NOT EXISTS data_imports (
    import_id       TEXT PRIMARY KEY,           -- UUID generated by the server
    uploaded_by     TEXT NOT NULL,              -- user email from JWT
    source_label    TEXT NOT NULL DEFAULT '',   -- hospital / source name supplied by user
    filename        TEXT NOT NULL,
    file_sha256     TEXT NOT NULL,              -- SHA-256 of the uploaded file (hex)
    layout          TEXT NOT NULL DEFAULT '',   -- 'flat' | 'multi_sheet'
    rows_total      INTEGER DEFAULT 0,
    sites_new       INTEGER DEFAULT 0,
    patients_new    INTEGER DEFAULT 0,
    visits_new      INTEGER DEFAULT 0,
    visits_updated  INTEGER DEFAULT 0,
    visits_skipped  INTEGER DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'pending',  -- 'pending'|'committed'|'failed'
    error_summary   JSONB DEFAULT '{}',
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_data_imports_created ON data_imports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_data_imports_status  ON data_imports(status);

-- RLS — same policy style as existing tables
ALTER TABLE data_imports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON data_imports FOR ALL USING (true);
